# Generated by Django 4.0.6 on 2022-08-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theevents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='file_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events_images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='num_of_attendees',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizetion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
